// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "UEImporterTutorialGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

UCLASS(BlueprintType)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialGameStateVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	/** Player received a tip about what to ask the Oracle */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* gotTip = nullptr;
	/** Player talked to Kirian before */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* visitedDialogue1 = nullptr;
	/** Player talked to the Oracle before */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* visitedDialogue2 = nullptr;
	/** checks processing of variables at end of a dialogue */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* testEnd = nullptr;
	
	 UUEImporterTutorialGameStateVariables() 
	{
		gotTip = CreateDefaultSubobject<UArticyBool>("gotTip");
		visitedDialogue1 = CreateDefaultSubobject<UArticyBool>("visitedDialogue1");
		visitedDialogue2 = CreateDefaultSubobject<UArticyBool>("visitedDialogue2");
		testEnd = CreateDefaultSubobject<UArticyBool>("testEnd");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		gotTip->Init<UArticyBool>(this, Store, TEXT("GameState.gotTip"), false);
		this->Variables.Add(gotTip);
		visitedDialogue1->Init<UArticyBool>(this, Store, TEXT("GameState.visitedDialogue1"), false);
		this->Variables.Add(visitedDialogue1);
		visitedDialogue2->Init<UArticyBool>(this, Store, TEXT("GameState.visitedDialogue2"), false);
		this->Variables.Add(visitedDialogue2);
		testEnd->Init<UArticyBool>(this, Store, TEXT("GameState.testEnd"), false);
		this->Variables.Add(testEnd);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UUEImporterTutorialGameStateVariables* GameState = nullptr;
	
	 UUEImporterTutorialGlobalVariables() 
	{
		/** create the namespaces */
		GameState = CreateDefaultSubobject<UUEImporterTutorialGameStateVariables>("GameState");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		GameState->Init(this);
		this->VariableSets.Add(GameState);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UUEImporterTutorialGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UUEImporterTutorialGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
