// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyGlobalVariables.h"
#include "UEImporterTutorialGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

UCLASS(BlueprintType)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialGameStateVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	/** Gracz otrzymal podpowiedz na temat NPC2 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* mamPodpowiedz = nullptr;
	/** Gracz rozmawial z pierwszym NPC */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* odpalonoDialog1 = nullptr;
	/** Gracz rozmawial z drugim NPC */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* odpalonoDialog2 = nullptr;
	/** Gdy wszystkie warunki testowe zostaly spelnione */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* testKoniec = nullptr;
	
	 UUEImporterTutorialGameStateVariables() 
	{
		mamPodpowiedz = CreateDefaultSubobject<UArticyBool>("mamPodpowiedz");
		odpalonoDialog1 = CreateDefaultSubobject<UArticyBool>("odpalonoDialog1");
		odpalonoDialog2 = CreateDefaultSubobject<UArticyBool>("odpalonoDialog2");
		testKoniec = CreateDefaultSubobject<UArticyBool>("testKoniec");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		mamPodpowiedz->Init<UArticyBool>(this, Store, TEXT("GameState.mamPodpowiedz"), false);
		this->Variables.Add(mamPodpowiedz);
		odpalonoDialog1->Init<UArticyBool>(this, Store, TEXT("GameState.odpalonoDialog1"), false);
		this->Variables.Add(odpalonoDialog1);
		odpalonoDialog2->Init<UArticyBool>(this, Store, TEXT("GameState.odpalonoDialog2"), false);
		this->Variables.Add(odpalonoDialog2);
		testKoniec->Init<UArticyBool>(this, Store, TEXT("GameState.testKoniec"), false);
		this->Variables.Add(testKoniec);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UUEImporterTutorialGameStateVariables* GameState = nullptr;
	
	 UUEImporterTutorialGlobalVariables() 
	{
		/** create the namespaces */
		GameState = CreateDefaultSubobject<UUEImporterTutorialGameStateVariables>("GameState");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		GameState->Init(this);
		this->VariableSets.Add(GameState);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UUEImporterTutorialGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UUEImporterTutorialGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
