// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "UEImporterTutorialInterfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="UEImporterTutorial Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UUEImporterTutorialObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IUEImporterTutorialObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UUEImporterTutorialDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="UEImporterTutorial Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UUEImporterTutorialObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IUEImporterTutorialObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UUEImporterTutorialDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
