// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "UEImporterTutorialGlobalVariables.h"
#include "UEImporterTutorialExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UUEImporterTutorialMethodsProvider : public UInterface { GENERATED_BODY() };
class IUEImporterTutorialMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UUEImporterTutorialGameStateVariables> GameState = nullptr;
	mutable TWeakObjectPtr<UUEImporterTutorialGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UUEImporterTutorialGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		GameState = gv ? gv->GameState : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UUEImporterTutorialMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UUEImporterTutorialExpressoScripts() 
	{
		Conditions.Add(1869598754, [&]
		{
			return ConditionOrTrue(
				!(*GameState->visitedDialogue1)
			);
		});
		Conditions.Add(-699477186, [&]
		{
			return ConditionOrTrue(
				(*GameState->visitedDialogue1)
			);
		});
		Instructions.Add(1012491589, [&]
		{
			(*GameState->visitedDialogue1) = true;
		});
		Instructions.Add(396507598, [&]
		{
			(*GameState->testEnd) = true;
		});
		Instructions.Add(1936233199, [&]
		{
			(*GameState->gotTip) = true;
		});
		Conditions.Add(1546660066, [&]
		{
			return ConditionOrTrue(
				!(*GameState->visitedDialogue2)
			);
		});
		Conditions.Add(-451859458, [&]
		{
			return ConditionOrTrue(
				(*GameState->visitedDialogue2)
			);
		});
		Instructions.Add(-823039280, [&]
		{
			(*GameState->visitedDialogue2) = true;
		});
		Conditions.Add(-432057496, [&]
		{
			return ConditionOrTrue(
				(*GameState->gotTip) == true
			);
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
