// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyDatabase.h"
#include "UEImporterTutorialExpressoScripts.h"
#include "UEImporterTutorialDatabase.generated.h"

UCLASS(BlueprintType)
class UEIMPORTERTUTORIAL_API UUEImporterTutorialDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UUEImporterTutorialDatabase() 
	{
		SetExpressoScriptsClass(UUEImporterTutorialExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UUEImporterTutorialDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UUEImporterTutorialDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UUEImporterTutorialGlobalVariables* GetGVs() const override
	{
		return static_cast<UUEImporterTutorialGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UUEImporterTutorialGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UUEImporterTutorialGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
