;METADATA=(Diff=true, UseCommands=true)
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=45903EFE49CAA11BCD0B10B4DAAB2BBF
ProjectName=Third Person Game Template

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsUFS=(Path="ArticyContent/Generated")
+DirectoriesToAlwaysCook=(Path="/Game/ArticyContent")

